
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int QUESTION = 10;
  public static final int CADENA = 21;
  public static final int SUMA = 11;
  public static final int FLECHA = 22;
  public static final int BARRA = 14;
  public static final int ID = 15;
  public static final int POR = 7;
  public static final int AST = 12;
  public static final int DP = 3;
  public static final int PT = 13;
  public static final int CARACTER = 16;
  public static final int LLC = 6;
  public static final int COMA = 9;
  public static final int PR_CONJ = 2;
  public static final int LLA = 5;
  public static final int EOF = 0;
  public static final int SEP = 4;
  public static final int error = 1;
  public static final int MIN = 18;
  public static final int PC = 8;
  public static final int ASCII = 20;
  public static final int MAY = 19;
  public static final int NUMBERS = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PR_CONJ",
  "DP",
  "SEP",
  "LLA",
  "LLC",
  "POR",
  "PC",
  "COMA",
  "QUESTION",
  "SUMA",
  "AST",
  "PT",
  "BARRA",
  "ID",
  "CARACTER",
  "NUMBERS",
  "MIN",
  "MAY",
  "ASCII",
  "CADENA",
  "FLECHA"
  };
}

